import crypto from 'crypto'
import { getConfigValue, getLicenseUsage, incrementLicenseUsage } from './db'
import { machineIdSync } from 'node-machine-id'

const SECRET_KEY = 'voiceclone-secret-v1-2026'
const FREE_MONTHLY_LIMIT = 5

/**
 * Universal key hashes (SHA256 of the formatted key).
 * Generated by `npx ts-node scripts/generate-key.ts`.
 * Add hashes here to enable universal keys that work on any machine.
 */
const VALID_KEY_HASHES: string[] = [
  // 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
]

function getMachineFingerprint(): string {
  try {
    return machineIdSync()
  } catch {
    return 'unknown-machine'
  }
}

function generateSerialCode(machineId: string): string {
  const data = `${machineId}:${SECRET_KEY}`
  const hash = crypto.createHash('sha256').update(data).digest('hex')
  const code = hash.substring(0, 16).toUpperCase()
  return `${code.substring(0, 4)}-${code.substring(4, 8)}-${code.substring(8, 12)}-${code.substring(12, 16)}`
}

function isUniversalKey(key: string): boolean {
  const hash = crypto.createHash('sha256').update(key).digest('hex')
  return VALID_KEY_HASHES.includes(hash)
}

export function validateLicenseKey(key: string): boolean {
  if (isUniversalKey(key)) {
    return true
  }

  const machineId = getMachineFingerprint()
  const expected = generateSerialCode(machineId)
  return key === expected
}

export function getLicenseInfo(): { isActivated: boolean; usageCount: number; monthLimit: number } {
  const licenseKey = getConfigValue('license_key') || ''
  const isActivated = licenseKey ? validateLicenseKey(licenseKey) : false
  const yearMonth = new Date().toISOString().slice(0, 7)
  const usageCount = getLicenseUsage(yearMonth)

  return {
    isActivated,
    usageCount,
    monthLimit: isActivated ? 999999 : FREE_MONTHLY_LIMIT,
  }
}

export function incrementUsage(): { allowed: boolean; remaining: number } {
  const info = getLicenseInfo()

  if (info.isActivated) {
    return { allowed: true, remaining: 999999 }
  }

  if (info.usageCount >= FREE_MONTHLY_LIMIT) {
    return { allowed: false, remaining: 0 }
  }

  const yearMonth = new Date().toISOString().slice(0, 7)
  incrementLicenseUsage(yearMonth)

  return { allowed: true, remaining: FREE_MONTHLY_LIMIT - info.usageCount - 1 }
}

export function getMachineId(): string {
  return getMachineFingerprint()
}
